#===============================================================================

#  merging scenario outcomes with baseline land-use and land-cover

#===============================================================================

# ==== packages =================================================================
  
library(raster)
library(sf)

#==== opening properties boundaries ============================================


path <- "shapefile path"
lim <- st_read(dsn=path,layer="properties_boundaries")



#==== land-use and land-cover (coffee,veg) =====================================

path2 <-  "raster files path"

coffee_veg = raster(file.path(path2,"land_use_cover.tif"))

#---- reclassify raster --------------------------------------------------------

m <- c(0, 0.09,0, 0.09,1,2,1,2,4)

rclmat <- matrix(m, ncol=3, byrow=TRUE)

coffee_veg_rc <- reclassify(coffee_veg,rclmat)

#==== opening scenarios outputs  ===============================================


path3 <- "path rasters generated by the scenarios"

list_farm_level <- grep(x = list.files(path = path3,
            pattern = "farm_level",full.names = T),pattern = ".tif",value=T)


list_regional_level <- grep(x = list.files(path = path3,pattern = "regional_level",full.names = T)
                    ,pattern = ".tif",value=T)

#==== resampling rasters =======================================================

# the rasters must be resampled in order to the mosaic function to work

#################################################
## IMPORTANT - possible raster classes

## 0,0 - (0)
## 0,2 - (2) remnant veg.
## 0,4 - (4) coffee
## 1,2 - (3) remnant veg overlaping restoration
## 1,4 - (5) restoration overlapping coffee
## 1,0 - (1) restoration
#################################################

path4 <- "path for resampled rasters"

#---- farm-level ---------------------------------------------------------------

i=4

for (i in seq(1,4,1)) {
   
   mosaic2 <- raster(list_farm_level[[i]])
   mos.res <- resample(mosaic2,coffee_veg,method='ngb')
   writeRaster(mos.res,file.path(path4,paste0("mosaic_farm_level_res",i*10,".tif")),overwrite=T)
   
}


#---- regional-level -----------------------------------------------------------

c=20
for (i in seq(1,length(list_regional_level),1)) {
   mosaic2 <- raster(list_regional_level[[i]])
   mos.res <- resample(mosaic2,coffee_veg,method='ngb')
   writeRaster(mos.res,file.path(path4,paste0("mosaic_regional_level_res",c,"_nopen_res.tif")))
   c=c+10
   
}



#==== mosaicing function =======================================================

mos <- function(restored_area,land_cover) {
  library(raster)
  flu <- raster::mosaic(restored_area,land_cover,fun=sum) 
  
}


#==== opening resampled rasters ================================================


list_farm_level_res <- grep(x = list.files(path = path4,pattern = "farm_level_res"
                    ,full.names = T),pattern = ".tif",value=T)


list_regional_level_res <- grep(x = list.files(path = path4,pattern = "regional_level_res",
                    full.names = T),pattern = ".tif",value=T)


path5 <- "path for merged data"

#--- farm-level ----------------------------------------------------------------

for (i in seq(1,4,1)) {
  mosaic <- mos(raster(list_farm_level_res[[i]]),coffee_veg_rc)
  writeRaster(mosaic,file.path("path5",paste0("futureLU_fl",10*i,"mosaic.tif")))
}


#--- regional-level -------------------------------------------------------------

c=20
for (i in seq(1,length(list_regional_level_res),1)) {
   mosaic <- mos(raster(list_regional_level_res[[i]]),coffee_veg_rc)
   writeRaster(mosaic,file.path("path5",paste0("futureLU_rl",c,"mosaic.tif")))
   c=c+10
   }


#==== reclassify rasters into 3 classes  ---------------------------------------

# 0 - all other uses
# 1 - natural vegetation
# 2 - coffee


lista_scen_fl <- grep(x = list.files(path = path5,pattern = "fl",full.names = T),
                      pattern = ".tif",value=T)

lista_scen_rl <- grep(x = list.files(path = path5,pattern = "rl",full.names = T),
                      pattern = ".tif",value=T)


m2 <- c(0, 0.9,0, 0.9,3,1,3,4,2,4,5,1)

rclmat2 <- matrix(m2, ncol=3, byrow=TRUE)

#---- fl -----------------------------------------------------------------------

for (i in seq(1,4,1)) {
   scen <- raster(lista_scen_fl[[i]])
   scen_rc <- reclassify(scen,rclmat2)
   writeRaster(scen_rc,file.path(path5,path5("futureLU_","fl_",i*10,"_rc.tif")))
   
}

#---- rl -----------------------------------------------------------------------


c=20
for (i in seq(1,3,1)) {
  scen <- raster(lista_scen_fl[[i]])
  scen_rc <- reclassify(scen,rclmat2)
  writeRaster(scen_rc,file.path(path5,path5("futureLU_","rl_",c,"_rc.tif")))
  c=c+10
  
}